repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-json
    exclude: ^((.*/)?\.vscode/(settings|launch)\.json|apps/vscode/settings-windows\.json|apps/vscode/devcontianer/devcontainer-terraform\.json)$
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: mdformat
    name: mdformat
    entry: mise format
    language: system
    pass_filenames: false
    types:
    - markdown
