repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-json
    exclude: ^(\.vscode/settings\.json|apps/vscode/settings-windows\.json|apps/vscode/devcontianer/devcontainer-terraform\.json)$
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.21.0
  hooks:
  - id: markdownlint-cli2
