theme: jekyll-theme-hacker
title: Notes to Self
tagline: Alex Sokolsky's Notes on Computers and Programming
description: Random Notes on Computers and Programming (mostly Python), Linux and Proxmox
author:
  name: Alex Sokolsky
  url: http://alexsokolsky.com
  location : "Campbell, CA, USA"
plugins:
  - jekyll-sitemap
search: true
google_site_verification: google3ad2904e499c26f9.html
social:
  name: Alex Sokolsky
  links:
    - https://www.linkedin.com/in/asokolsky
    - https://github.com/asokolsky
social_links:
  github: asokolsky
  linkedin: asokolsky
