theme: jekyll-theme-hacker
title: Notes to Self
description: Alex Sokolsky's Notes on Computers and Programming
author:
  name: Alex Sokolsky
  url: http://alexsokolsky.com
plugins:
  - jekyll-sitemap