theme: jekyll-theme-hacker
title: Notes to Self
tagline: Alex Sokolsky's Notes on Computers and Programming
description: Random Notes on Computers, Programming (mostly Python), Linux and Proxmox
author:
  name: Alex Sokolsky
  url: http://alexsokolsky.com
  location : "Campbell, CA, USA"
plugins:
  - jekyll-sitemap
  - jekyll-spaceship
search: true
google_site_verification: google3ad2904e499c26f9.html
social:
  name: Alex Sokolsky
  links:
    - https://www.linkedin.com/in/asokolsky
    - https://github.com/asokolsky
social_links:
  github: asokolsky
  linkedin: asokolsky
github_username:  asokolsky
linkedin_username: asokolsky
comments:
  provider: "disqus"
  disqus:
    shortname: "asokolsky-github-io"
defaults: # set page variable defaults
  -
    scope:
      path: ""      # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: "Alex Sokolsky"
      comments: true
  -
    scope:
      path: ""
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
