#!/bin/bash
#
# Script is inspired by
# https://gist.github.com/moritzmhmk/48e5ed9c4baa5557422f16983900ca95
# https://gist.github.com/nunofgs/84861ee453254823be6b069ebbce9ad2
#
# Set default values for environment variables
: "${HTTP_URL:=https://connect.prusa3d.com/c/snapshot}"
: "${DELAY_SECONDS:=10}"
: "${LONG_DELAY_SECONDS:=60}"
# FINGERPRINT is a random string with at least 16 characters
: "${FINGERPRINT1:=123456789012345678}"
: "${FINGERPRINT2:=123456789012345678}"
# CAMERA_TOKEN generated by the Connect server
: "${CAMERA_TOKEN1:=put the token here}"
: "${CAMERA_TOKEN2:=put the token here}"

# Grab a frame from the webcam using FFmpeg, -video_size 1280x720
function grab_a_frame {
    local device=$1
    local out_path=$2
    ffmpeg -loglevel warning -y -f video4linux2 -input_format mjpeg \
        -i "$device" -video_size 1280x720 -vframes 1 -f mjpeg "$out_path"
}


# POST the image to the HTTP URL using curl
function upload_a_frame {
    local fingerprint=$1
    local token=$2
    local frame_path=$3
    # POST the image to the HTTP URL using curl
    curl -X PUT "$HTTP_URL" \
      -H "accept: */*" \
      -H "content-type: image/jpg" \
      -H "fingerprint: $fingerprint" \
      -H "token: $token" \
      --data-binary "@$frame_path" --no-progress-meter --compressed
}

while true; do
    # Reset delay to the normal value
    DELAY=$DELAY_SECONDS
    grab_a_frame /dev/video0 /tmp/video0.jpg
    if [ $? -eq 0 ]; then
        upload_a_frame "$FINGERPRINT1" "$CAMERA_TOKEN1" /tmp/video0.jpg
    else
        echo "Error reading /dev/video0. Retrying in ${LONG_DELAY_SECONDS}s..."
        DELAY=$LONG_DELAY_SECONDS
    fi
    grab_a_frame /dev/video2 /tmp/video2.jpg
    if [ $? -eq 0 ]; then
        upload_a_frame "$FINGERPRINT1" "$CAMERA_TOKEN2" /tmp/video2.jpg
    else
        echo "Error reading /dev/video2. Retrying in ${LONG_DELAY_SECONDS}s..."
        DELAY=$LONG_DELAY_SECONDS
    fi
    sleep "$DELAY"
done
