# .zprofile is similar to .zlogin, except that it is sourced before .zshrc.
# .zprofile is meant as an alternative to .zlogin for ksh fans;
# the two are not intended to be used together,
# although this could certainly be done.

eval "$(ssh-agent -s)"
# add more IDs as needed
ssh-add -q ~/.ssh/id_rsa ~/.ssh/latitude_id_rsa
