# .zprofile is similar to .zlogin, except that it is sourced before .zshrc.
# .zprofile is meant as an alternative to .zlogin for ksh fans;
# the two are not intended to be used together,
# although this could certainly be done.
if [ -f ~/.zsh_aliases ]; then
    . ~/.zsh_aliases
fi

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval "$(ssh-agent -s)"
    # add more IDs as needed
    #ssh-add
    ssh-add -q ~/.ssh/latitude_id_rsa ~/.ssh/t14g3
    # to check what was loaded use ssd-add -l
fi
