# .zshenv is sourced on all invocations of the shell, unless the -f option is
# set. It should contain commands to set the command search path, plus other
# important environment variables.
# .zshenv should NOT contain commands that produce output or assume the shell
# is attached to a tty.

export AWS_DEFAULT_REGION=us-east-1
export GOROOT=$HOME/go
#export VAULT_ADDR=https://vault.foo.bar/
export PDSH_RCMD_TYPE=ssh
