# .zshenv is sourced on all invocations of the shell, unless the -f option is
# set. It should contain commands to set the command search path, plus other
# important environment variables.
# .zshenv should NOT contain commands that produce output or assume the shell
# is attached to a tty.

export AWS_DEFAULT_REGION=us-east-1
export GOROOT=$HOME/go
export PDSH_RCMD_TYPE=ssh
export EDITOR=emacs
if [ "$INSIDE_EMACS" ]; then
    export PAGER="/usr/bin/more"
else
    export PAGER="/usr/bin/less"
    export LESS="-isR"
    #alias lv="less"
fi

case "$AWS_VAULT" in
    "dev-from-security"|"dev-from-sso" )
        export KUBECONFIG="$HOME/.kube/dev-config" ;;
    *)
        export KUBECONFIG="$HOME/.kube/config" ;;
esac
