# .zshrc is sourced in interactive shells.
# Should contain commands to set up aliases, functions, options, key bindings,
# etc.

# Set up the prompt
autoload -Uz promptinit
promptinit
prompt suse
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '[%b]'
#zstyle ':vcs_info:git*' actionformats "%r/%S %b %m%u%c "
#zstyle ':vcs_info:git*' actionformats "%s  %r/%S %b %m%u%c "

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# The following lines were added by compinstall
#zstyle :compinstall filename '~/.zshrc'
#autoload bashcompinit && bashcompinit
#autoload -Uz compinit && compinit
# End of lines added by compinstall

# install CLI completions
source <(kubectl completion zsh)
complete -C '/usr/local/bin/aws_completer' aws

#source $ZSH/oh-my-zsh.sh
#
# ensure the history is NOT shared between terminals
# https://linux.die.net/man/1/zshoptions
#
unsetopt inc_append_history
unsetopt share_history